"""
briefing_service.py

Anara Daily Briefing — one command ("briefing hari ini") composes everything the
user needs into a single holographic card: date/time, weather, priority to-dos,
active projects and a short spoken summary.

Weather is generated by the same fast Gemini model already used elsewhere; all
other data comes straight out of the SQLite brain.
"""

import asyncio
import json
import logging
import re
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from google import genai
from google.genai import types

logger = logging.getLogger(__name__)

WIB = timezone(timedelta(hours=7))

_DAYS_ID = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"]
_MONTHS_ID = [
    "Januari", "Februari", "Maret", "April", "Mei", "Juni",
    "Juli", "Agustus", "September", "Oktober", "November", "Desember",
]

_WEATHER_PROMPT = (
    "Kamu adalah modul cuaca untuk asisten Anara. Berikan perkiraan cuaca yang masuk akal "
    "untuk kota {city}, Indonesia pada {date_str} pukul {time_str} WIB.\n"
    "Gunakan pengetahuan iklim umum Indonesia (musim, suhu tipikal kota tersebut).\n\n"
    "KEMBALIKAN HANYA JSON VALID (tanpa markdown):\n"
    '{"city": "...", "temp_c": 30, "condition": "Cerah Berawan", "humidity": 75, '
    '"wind_kmh": 12, "advice": "saran singkat 1 kalimat"}'
)


def _now_parts() -> Dict[str, str]:
    now = datetime.now(WIB)
    return {
        "day": _DAYS_ID[now.weekday()],
        "date_str": f"{_DAYS_ID[now.weekday()]}, {now.day} {_MONTHS_ID[now.month - 1]} {now.year}",
        "time_str": now.strftime("%H:%M"),
        "hour": now.hour,
    }


def _greeting(hour: int) -> str:
    if hour < 4:
        return "Masih larut"
    if hour < 11:
        return "Selamat pagi"
    if hour < 15:
        return "Selamat siang"
    if hour < 18:
        return "Selamat sore"
    return "Selamat malam"


def _parse_json(raw: str) -> Optional[Dict[str, Any]]:
    if not raw:
        return None
    txt = re.sub(r"^```(?:json)?\s*", "", raw.strip())
    txt = re.sub(r"\s*```$", "", txt)
    if "{" not in txt:
        return None
    try:
        return json.loads(txt[txt.find("{"): txt.rfind("}") + 1])
    except json.JSONDecodeError:
        return None


async def _fetch_weather(client: genai.Client, city: str) -> Optional[Dict[str, Any]]:
    parts = _now_parts()
    prompt = (
        _WEATHER_PROMPT
        .replace("{city}", city)
        .replace("{date_str}", parts["date_str"])
        .replace("{time_str}", parts["time_str"])
    )
    cfg = types.GenerateContentConfig(max_output_tokens=200, temperature=0.3)
    for mdl in ["gemini-3.5-flash-lite", "gemini-3.1-flash-lite"]:
        try:
            res = await asyncio.wait_for(
                client.aio.models.generate_content(model=mdl, contents=prompt, config=cfg),
                timeout=5.0,
            )
            if res and res.text:
                data = _parse_json(res.text)
                if data:
                    return data
        except Exception as e:
            logger.warning(f"[Briefing] Weather model {mdl} failed: {e}")
    return None


def is_briefing_request(text: str) -> bool:
    """Zero-token gate for 'briefing hari ini' style requests."""
    t = (text or "").lower()
    if not t:
        return False
    patterns = [
        r"\bbriefing\b",
        r"\b(?:apa|gimana|bagaimana)\s+(?:agenda|jadwal|rencana)\s+(?:hari\s+ini|hariku|saya|aku)\b",
        r"\bagenda\s+hari\s+ini\b",
        r"\bjadwal\s+hari\s+ini\b",
        r"\brangkum(?:an)?\s+hari\s+ini\b",
        r"\bupdate\s+(?:hari\s+ini|dong|harian)\b",
        r"\bringkasan\s+(?:hari\s+ini|harian|pagi)\b",
        r"\bapa\s+saja\s+(?:tugas|agenda)\s+(?:ku|saya|hari\s+ini)\b",
    ]
    return any(re.search(p, t) for p in patterns)


async def generate_daily_briefing(
    client: genai.Client,
    memory_engine: Any,
    speaker_name: Optional[str] = None,
    city: str = "Jakarta",
) -> Dict[str, Any]:
    """
    Builds the full briefing payload: spoken summary + structured HUD card.
    """
    parts = _now_parts()
    name = speaker_name or "Tamu"
    greeting = _greeting(parts["hour"])

    # ── Gather brain data ──
    todos: List[Dict[str, Any]] = []
    projects: List[Dict[str, Any]] = []
    try:
        raw_todos = memory_engine.get_notes_and_todos(speaker_name=speaker_name)
        todos = [t for t in raw_todos if not t.get("is_completed")]
    except Exception as e:
        logger.warning(f"[Briefing] todo fetch failed: {e}")
    try:
        if speaker_name:
            projects = [
                p for p in memory_engine.get_projects_for_speaker(speaker_name)
                if (p.get("status") or "active").lower() == "active"
            ]
    except Exception as e:
        logger.warning(f"[Briefing] project fetch failed: {e}")

    weather = await _fetch_weather(client, city)

    # ── Compose the spoken summary via LLM for natural, non-hardcoded delivery ──
    reply_text = ""
    try:
        synth_prompt = (
            f"Kamu adalah Anara. Susunlah narasi briefing harian singkat yang hangat, cerdas, dan membakar semangat untuk {name}.\n"
            f"Waktu: {parts['date_str']}, pukul {parts['time_str']} WIB.\n"
            f"Cuaca: {weather.get('condition') if weather else 'Cerah'}" + (f", suhu {weather.get('temp_c')}°C" if weather and weather.get('temp_c') else "") + "\n"
            f"Tugas/To-do hari ini: {[t.get('title') for t in todos] if todos else 'Semua to-do beres / lapang'}\n"
            f"Proyek aktif: {[p.get('name') for p in projects] if projects else 'Tidak ada proyek baru'}\n\n"
            "Aturan: Ucapkan dalam 2-3 kalimat Bahasa Indonesia yang natural, mengalir, dan hangat. "
            "Dilarang kaku seperti robot atau format formulir."
        )
        for mdl in ["gemini-3.5-flash-lite", "gemini-3.1-flash-lite"]:
            try:
                cfg_synth = types.GenerateContentConfig(max_output_tokens=180, temperature=0.7)
                res_synth = await asyncio.wait_for(
                    client.aio.models.generate_content(model=mdl, contents=synth_prompt, config=cfg_synth),
                    timeout=4.0
                )
                if res_synth and res_synth.text:
                    reply_text = res_synth.text.strip()
                    break
            except Exception:
                continue
    except Exception as e_synth:
        logger.warning(f"[Briefing] LLM synthesis fallback: {e_synth}")

    if not reply_text:
        lines: List[str] = [f"{greeting} {name}! Ini rangkuman singkat untuk hari {parts['date_str']}."]
        if weather:
            cond = weather.get("condition", "cerah")
            lines.append(f"Cuaca saat ini {str(cond).lower()}.")
        if todos:
            titles = [(t.get("title") or "").strip() for t in todos if (t.get("title") or "").strip()]
            lines.append(f"Ada {len(titles)} agenda tugas yang menantimu, salah satunya {titles[0]}.")
        else:
            lines.append("Agenda tugasmu hari ini cukup santai dan lapang.")
        reply_text = " ".join(lines)

    # ── Structured card for the HUD ──
    card = {
        "date_str": parts["date_str"],
        "time_str": parts["time_str"],
        "greeting": greeting,
        "speaker": name,
        "weather": (
            {
                "city": weather.get("city", city),
                "temp_c": weather.get("temp_c"),
                "condition": weather.get("condition"),
                "humidity": weather.get("humidity"),
                "wind_kmh": weather.get("wind_kmh"),
                "advice": weather.get("advice"),
            }
            if weather
            else None
        ),
        "todos": [
            {
                "title": (t.get("title") or "").strip(),
                "content": (t.get("content") or "").strip() or None,
                "due": (t.get("due_date") or "").strip() or None,
            }
            for t in todos[:6]
        ],
        "projects": [
            {
                "name": (p.get("name") or "").strip(),
                "goal": (p.get("goal") or "").strip() or None,
                "tech": (p.get("tech_stack") or "").strip() or None,
            }
            for p in projects[:4]
        ],
    }

    logger.info(
        f"[Briefing] Composed for {name}: weather={'yes' if weather else 'no'}, "
        f"todos={len(card['todos'])}, projects={len(card['projects'])}"
    )

    return {"reply_text": reply_text, "briefing_data": card}
